### PR TITLE
CLUSTER-7853: dashboard migration checker

### PR DESCRIPTION
**Pull request by SIMULATAN**
This PR adds a `dashboardMigrationChecker.py` script that, as the name suggests, checks recently used dashboards and prints if they can be migrated to 3rd gen.
The script can output the results in various formats:
- Markdown (`markdown`)
  - formatted as a table
- CSV (`csv`)
- JSON (`json`)
  - each line is a new JSON object
  - => all output lines in one are **not** valid JSON!
- JSON Array (`json_array`)
  - JSON Array as the root containing the same objects as normal JSON

## Todo
- [x] Multithreading
  - [x] basic multithreading
    - ignores the ratelimits
  - [x] account for rate limiting
  - [x] make parallel requests configurable
    - this is because the value varies from tenant to tenant
- [x] Print why the status is "unknown"
  - maybe show other tile names?
- [ ] Figure out what to separate tiles with
  - some formats don't support lists, for those, we have to use a separator
  - to simplify parsing, this separator should exist in neither the format in question nor metrics selector
  - [ ] CSV
    - currently:
      - `|` between tiles
      - ` ` between expressions
  - [ ] Markdown
    - currently:
      - `;` between tiles
      - ` ` between expressions

## Context
This script was requested in CLUSTER-7853

## Screenshots
...can be found attached to the ticket

<hr>

Feedback is appreciated!

### CODE REVIEW

**Comment by SIMULATAN** [comment]
After implementing basic multithreading, I observed astronomical results with an increase in speed of up to 6x with only 24 dashboards. The impact will probably be even stronger with more dashboards.
Some profiling data can be found in [this gist](https://gist.github.com/SIMULATAN/572385e85f4fb018a41bfecae24cba07).
I'll update it with more results soon™

**Comment by SIMULATAN** [comment]
Update: just tested the script with 1107 Dashboards with a total of 12431 `DATA_EXPLORER` tiles. Processing time: **161.33** seconds! Just imagine that with a single thread!

The failing dashboard has a total of 229 `DATA_EXPLORER` tiles, which unfortunately just isn't doable in a duration of 60 seconds. Since every transpile takes a second on average, said dashboard would need at least ~230 seconds to complete.

Additionally, scaling to infinity isn't good in this case. The backend can only handle so much and the current multithreading is basically a DDOS attack that actually outputs the response.

To fix this, I propose to use ThreadPools with configurable sizes. Additionally, the transpile calls should be async with a separate ThreadPool. This *should* 1) avoid overloading the server and 2) improve individual dashboard loading times at the expense of increasing the total running time.

However, with only 160 seconds of running time for a insane amount of dashboards, such an increase probably won't be too big of an issue.
Additionally, reliability and stability is key here, therefore, a drop in speed is acceptable to an extend.

All in all, multithreading here is crucial at scale, with 12400 tiles taking a second each to transpile, the total running time would be well above **3 hours**!

**Comment by SIMULATAN** [comment]
More profiling data!

Dashboards: 1107
Tiles: 12435

| Dashboard threads | Transpile threads | Processing Times |
|---|---|---|
| 500  | 1000 | 103.1s, 103.48s, 101.45s |
| 1000 | 1000 | 107.85s, 101.44s, 97.62s |
| 500  | 2000 | 92s, 91.89s, 94.38s* |

\* exception occurred => UNRELIABLE!

The current algorithm awaits every tile separately. Within a dashboard, only tiles with multiple expressions are sent to separate threads.

Please note that these measurements are far from scientific. I manually executed the program with different pool sizes and noted the results. There are no fixed delays between runs or anything like that, this is just to check if there are any major issues to consider.
These numbers were recorded on a dev tenant (gmg80500), they will probably be different for your server.

**Comment by SIMULATAN** [comment]
V4 with sorted dashboards:

| Dashboard threads | Transpile threads | Processing times |
|---|---|---|
| 100 | 1000 | 47.34s, 44.94s |
| 250 | 1000 | 50.04s, 49.73s |

In this version, the dashboards are sorted based on their total expression count in descending order. This allows huge dashboards to be processed first and smaller ones at the end. This leads to optimal thread pool utilization throughout the application lifecycle and thus a nice increase in speed.

All the optimizations in the multithreading logic makes processing **3.5x** as fast compared to the basic version! (and there are no failing dashboards either)

**Comment by SIMULATAN** [comment]
Made it so setting the timeout to 0 disables the sidecar completely.
This is a bit dangerous as, well, there's no timeout, but on the bright side, it halves the amount of required dashboard threads.

| Sidecar? | Dashboard threads | Transpile threads | Processing times |
|---|---|---|---|
| No | 100 | 1000 | 45.6s, 43.33s, 44.25s |
| Yes | 100 | 1000 | 56.08s, 43.89s, 43.47s |

As evidenced by the measurements, in most cases, it's probably not worth it. The difference is marginal and the downside of having no timeout safety takes precedence here.

**Comment by SIMULATAN** [comment]
With this fix, I'll mark this PR as ready for review. Feel free to suggest improvements.

**Review by stefan-moschinski-dynatrace — APPROVED** [review]

**Pull request merged**
